name: Test Workflow
on: [push]
jobs:
  setup_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo $RUNNER_TEMP
      - uses: brandonc/setup-terraform@brandonc/tmp_cli_config
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform plan -no-color
