name: Test Workflow
on: [push]
jobs:
  setup_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        env:
          TF_CLI_CONFIG_FILE: ${{ env.RUNNER_TEMP }}/.terraformrc
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
        env:
          TF_CLI_CONFIG_FILE: ${{ env.RUNNER_TEMP }}/.terraformrc
      - run: terraform plan -no-color
        env:
          TF_CLI_CONFIG_FILE: ${{ env.RUNNER_TEMP }}/.terraformrc
